(define (rectangle w h)
    (cons w h))
(define (width-rectangle rect)
    (car rect))
(define (height-rectangle rect)
    (cdr rect))
(define (perimeter rect)
    (* 2 (+ (width-rectangle rect) (height-rectangle rect))))
(define (area rect)
    (* (width-rectangle rect) (height-rectangle rect)))