(load "2.09.scm")
(define (make-center-width c w)
    (make-interval (- c w) (+ c w)))
(define (center i)
    (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
    (/ (- (upper-bound i) (lower-bound i)) 2))
(define (make-center-percent c p)
    (make-interval (- c (* c p))
                   (+ c (* c p))))
(define (percent i)
    (/ (width i) (center i)))