(define (same-parity first . next)
    (define (rec filter lst)
        (if (null? lst)
            (list)
            (if (filter (car lst))
                (append (list (car lst)) 
                        (rec filter (cdr lst)))
                (rec filter (cdr lst)))))
    (if (odd? first)
        (rec odd? (append (list first) next))
        (rec even? (append (list first) next))))