(load "2.48.scm")
(define (outline-painter)
    (define left-top (make-vect 0.0 1.0))
    (define left-bottom (make-vect 0.0 0.0))
    (define right-top (make-vect 1.0 1.0))
    (define right-bottom (make-vect 1.0 0.0))
    (define top (make-segment left-top right-top))
    (define bottom (make-segment left-bottom right-bottom))
    (define left (make-segment left-top left-bottom))
    (define right (make-segment right-top right-bottom))
    (segments->painter (list top bottom left right)))
(define (x-painter)
    (define left-top (make-vect 0.0 1.0))
    (define left-bottom (make-vect 0.0 0.0))
    (define right-top (make-vect 1.0 1.0))
    (define right-bottom (make-vect 1.0 0.0))
    (define left-top-to-right-bottom (make-segment left-top right-bottom))
    (define right-top-to-left-bottom (make-segment right-top left-bottom))
    (segments->painter (list left-top-to-right-bottom
                             right-top-to-left-bottom)))