(load "2.56.scm")
(define (make-sum . a)
    (if (= (length a) 1)
        (if (= (length (car a)) 2)
            (list '+ (caar a) (cadr (car a)))
            (list '+ (caar a) (make-sum (cdr (car a)))))
        (if (<= (length a) 2)
            (list '+ (car a) (cadr a))
            (list '+ (car a) (make-sum (cdr a))))))
(define (make-product . a)
    (if (= (length a) 1)
        (if (= (length (car a)) 2)
            (list '* (caar a) (cadr (car a)))
            (list '* (caar a) (make-product (cdr (car a)))))
        (if (<= (length a) 2)
            (list '* (car a) (cadr a))
            (list '* (car a) (make-product (cdr a))))))