(define (entry tree) (car tree))
(define (value tree) (car tree))
(define (left-branch tree) (cadr tree))
(define (right-branch tree) (caddr tree))
(define (make-tree entry value left right)
  (list entry value left right))
(define (lookup x set)
  (cond ((null? set) false)
        ((= x (entry set)) (value set))
        ((< x (entry set))
         (lookup x (left-branch set)))
        ((> x (entry set))
         (lookup x (right-branch set)))))