(load "2.68.scm")
(define (generate-huffman-tree pairs)
  (successive-merge (make-leaf-set pairs)))
(define (successive-merge set)
  (cond ((= 0 (length set)) '())
        ((= 1 (length set)) (car set))
        (else (successive-merge (adjoin-set (make-code-tree (car set)
                                                            (cadr set))
                                            (cddr set))))))