// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, consoler, executer, instructions, parser;

  canvas = document.getElementById('Canvas_Logo');

  parser = new Parser;

  executer = new Executer(canvas);

  consoler = new Consoler;

  instructions = parser.parse('FD 100 RT 90 FD 100 RT 90 FD 100 RT 90 FD 100');

  console.log(instructions);

  executer.execute(instructions);

}).call(this);
