// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, commandCallback, consoleDiv, consoler, executer, parser;

  canvas = document.getElementById('Canvas_Logo');

  consoleDiv = document.getElementById('Div_Console');

  parser = new Parser;

  executer = new Executer(canvas);

  commandCallback = function(source) {
    var instructions;
    instructions = parser.parse(source);
    return executer.execute(instructions);
  };

  consoler = new Consoler(consoleDiv, 5, commandCallback);

  document.onkeyup = consoler.onkeyup;

}).call(this);
