(define (average x y)
  (/ (+ x y) 2))
(define (improve guess x)
  (average guess (/ x guess)))
(define (good-enough? old new)
  (< (/ (abs (- new old)) old) 0.001))
(define (sqrt-iter guess x)
  (if (good-enough? guess (improve guess x))
       (improve guess x)
       (sqrt-iter (improve guess x)
                  x)))
(define (sqrt x)
  (sqrt-iter 1.0 x))
(square (sqrt 0.00009))