(define (improve guess x)
        (/ (+ (/ x (square guess))
              (* 2 guess)) 
           3))
(define (good-enough? old new)
        (< (/ (abs (- new old)) old)
           0.001))
(define (cube-root-iter guess x)
        (if (good-enough? guess (improve guess x))
            (improve guess x)
            (cube-root-iter (improve guess x) x)))
(define (cube-root x)
        (cube-root-iter 1.0 x))
(define (cube x) (* x x x))
(cube (cube-root 128.0))