(load "1.21.scm")
(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(define (search-for-primes n m) 
  (timed-prime-test n)
  (if (prime? n)
      (if (> m 1)
          (search-for-primes (+ n 2) (- m 1)))
      (search-for-primes (+ n 2) m)))
(search-for-primes 1001 3)
(search-for-primes 10001 3)
(search-for-primes 100001 3)
(search-for-primes 1000001 3)