(define tolerance 0.00001)
(define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
        (< (abs (- v1 v2)) tolerance))
    (define (try guess i)
        (newline)
        (display "Step: ")
        (display i)
        (display " Guess: ")
        (display guess)
        (let ((next (f guess)))
            (if (close-enough? guess next)
                next
                (try next (+ i 1)))))
    (try first-guess 1))
(fixed-point (lambda (x) (/ (log 1000) (log x))) 2.0)
(fixed-point (lambda (x) (* (+ x (/ (log 1000) (log x))) 0.5)) 2.0)