(load "1.16.scm")
(load "1.35.scm")
(load "1.43.scm")
(define (average x y)
    (* (+ x y) 0.5))
(define (average-damp f)
    (lambda (x) (average x (f x))))
(define (average-damp-n f n)
    ((repeated average-damp n) f))
(define (damp-root n times)
    (lambda (x)
        (fixed-point (average-damp-n (lambda (y)
                                         (/ x (fast-expt y (- n 1))))
                                     times) 
                     1.0)))