(load "1.23.scm")
(define (carmichael? n)
  (define (carmichael-iter i n)
    (cond ((= i n) #t)
          ((carmichael-test? i n) (carmichael-iter (+ i 1) n))
          (else #f)))
  (define (carmichael-test? i n)
    (= (expmod i n n) i))
  (carmichael-iter 1 n))
(display (carmichael? 561))
(display (carmichael? 1105))
(display (carmichael? 1729))
(display (carmichael? 2465))
(display (carmichael? 2821))
(display (carmichael? 6601))