(define (cons x y)
    (* (exp 2 x)
       (exp 3 y)))
(define (car z)
    (if (=  0 (remainder z 2))
        (+ 1 (car (/ z 2)))
        0))
(define (cdr z)
    (if (= 0 (remainder z 3))
        (+ 1 (cdr (/ z 3)))
        0))