(define (make-rat n d) 
    (if (< d n)
        (cons (- n) (- d))
        (cons n d)))
(define (numer x) (car x))
(define (denom x) (cdr x))
(define (print-rat x)
    (newline)
    (display (numer x))
    (display "/")
    (display (denom x)))