#ifndef DEFINATIONEDITORSELECTIONTYPE_H
#define DEFINATIONEDITORSELECTIONTYPE_H

class DefinationEditorSelectionType
{
public:
    enum EditorSelectionType
    {
        EDITOR_SELECTION_NULL,
        EDITOR_SELECTION_EMPTY,
        EDITOR_SELECTION_GO_OPERATOR,
        EDITOR_SELECTION_GO_SIGNAL,
        EDITOR_SELECTION_GO_TEXT,
        EDITOR_SELECTION_GO_MARKOV_OPERATOR,
        EDITOR_SELECTION_GO_MARKOV_EQUIVALENT,
        EDITOR_SELECTION_GO_MARKOV_COMMON_CAUSE,
        EDITOR_SELECTION_GO_SELECTION
    };
};

#endif // DEFINATIONEDITORSELECTIONTYPE_H
